version: '3'

services:
  db:
    image: postgres:12-alpine
    hostname: ismpdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
  backend:
    image: richyen/ismp-backend
    build: ./backend
    links:
      - "db:ismpdb"
    volumes:
      - ./backend:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - db
    entrypoint:
      - "/app/api/api-entrypoint.sh"
  frontend:
    image: richyen/ismp-frontend
    build: ./frontend
    command: ["yarn", "start"]
    stdin_open: true
    tty: true
    environment:
      REACT_APP_API_HOST: "http://localhost"
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules:
